### ISSUE TITLE
Ignore branches with open PRs

### ISSUE THREAD

**Issue by slawekGoszcz** [fpicalausa/remove-stale-branches#18]
Hi, I found your action on marketplace and it's pretty useful but there is one functionality that I could benefit from. In some cases I need to leave branches with Open PRs unmodified. 

I have prepared a PR. If you could take a look.

**Comment by slawekGoszcz** [comment]
https://github.com/fpicalausa/remove-stale-branches/pull/19

**Comment by ccoVeille** [comment]
Thanks for coding this. This is the thing I was afraid of when using the tool
