### ISSUE TITLE
stale-branch-message hard-coded days and templating

### ISSUE THREAD

**Issue by electriquo** [fpicalausa/remove-stale-branches#6]
i might be missing something, but by looking it seems that `days-before-branch-stale` isn't being replaced in `stale-branch-message` template:
- https://github.com/fpicalausa/remove-stale-branches/blob/b9de60cd91c381c43b15203f39ffeb2baf7574f9/src/cli.ts#L17
- https://github.com/fpicalausa/remove-stale-branches/blob/b9de60cd91c381c43b15203f39ffeb2baf7574f9/README.md?plain=1#L28

1. does the `60` days is being replaced with `days-before-branch-stale`?
2. what is the template format/attributes/vars/syntax of `stale-branch-message`?

**Comment by fpicalausa** [comment]
@electriquo the message formatting definitely was added as an after thought without much love. 
Let me document it in the README. 

For anyone stumbling upon this issue, the replacements are done in [commitComments](https://github.com/fpicalausa/remove-stale-branches/blob/ebb2ebb3c6ea0782d9e03dc8a3c66a56f843e824/src/commitComments.ts#L31) and here the token is `{daysBeforeBranchStale}` (camelCase)
