### ISSUE TITLE
Declare license

### ISSUE THREAD

**Issue by yrtimiD** [fpicalausa/remove-stale-branches#9]
Many orgs require clear license declaration and included license file to be able to use your action.
Will appreciate if you can add one.

The package.json declares "UNLICENSED", is it: 
> "you do not wish to grant others the right to use a private or unpublished package under any terms" 

as explained in https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license ?

or it's the https://spdx.org/licenses/Unlicense.html ?

**Comment by fpicalausa** [comment]
Thanks for flagging. Originally, it was indeed the former (i.e. not providing any rights), but it makes more sense to properly license it at this point.
